name: Robot Update Anime Otomatis

on:
  schedule:
    # Robot jalan otomatis setiap 6 jam (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *' 
  workflow_dispatch:      
    # Tombol sakti untuk menjalankan manual kapan saja

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Ambil Kode dari Repo
        uses: actions/checkout@v4

      - name: 2. Setup Python Versi Terbaru
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Menggunakan versi 3.10 yang lebih stabil

      - name: 3. Install Library dari Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Jalankan Scraper Massal
        run: python scraper.py
